---
- name: Elastic installation
  hosts: elastic
  become: true
  tasks:
    - name: Update repo
      apt:
        update_cache: yes

    - name: Download elasticsearch
      copy:
        src: /home/ansible-vm/elasticsearch-8.13.2-amd64.deb
        dest: /tmp/elasticsearch-8.13.2-amd64.deb
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0764'
        force: yes
      register: el_inst
    
    - name: Install elastic
      apt:
        deb: /tmp/elasticsearch-8.13.2-amd64.deb

    - name: Replace elasticsearch config
      template:
        src: /home/ansible-vm/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: elasticsearch
        group: elasticsearch
        mode: '0666'
      register: config_check

    - name: Start up elasticsearch
      service:
        name: elasticsearch
        enabled: true
        state: restarted
      when: config_check.changed

    - name: Check 9200 
      uri:
        url: http://ru-elk-a.local:9200
        status_code: 200
        return_content: true
